spring:
  application:
   name: User-Service
  datasource:
    url: jdbc:mysql://localhost:3306/usdb
    username: root
    password: root
  
    driver-class-name: com.mysql.cj.jdbc.Driver
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
    
    database-platform: org.hibernate.dialect.MySQL8Dialect
eureka:
  instance:
    hostname: localhost 
    ip-address: true  
 
    
      
    
    
    
