

spring:
  application:
   name: Contact-Service
  datasource:
    url: jdbc:mysql://localhost:3306/ravikiran
    username: root
    password: root
  
    driver-class-name: com.mysql.cj.jdbc.Driver
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
    
    database-platform: org.hibernate.dialect.MySQL8Dialect
    
    
server:
  port: 8082
eureka:
 instance:
    ip-address: true  
 